Extract libraries

In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Extract and preparation data

In [5]:
data_negative = pd.read_csv('data/processedNegative.csv')
data_neutral = pd.read_csv('data/processedNeutral.csv')
data_positive = pd.read_csv('data/processedPositive.csv')

In [6]:
data_negative.head(5)

Empty DataFrame
Columns: [How unhappy  some dogs like it though, talking to my over driver about where I'm goinghe said he'd love to go to New York too but since Trump it's probably not, Does anybody know if the Rand's likely to fall against the dollar? I got some money  I need to change into R but it keeps getting stronger unhappy , I miss going to gigs in Liverpool unhappy , There isnt a new Riverdale tonight ? unhappy , it's that A*dy guy from pop Asia and then the translator so they'll probs go with them around Aus unhappy , Who's that chair you're sitting in? Is this how I find out. Everyone knows now. You've shamed me in pu, don't like how jittery caffeine makes me sad , My area's not on the list unhappy  think I'll go LibDems anyway, I want fun plans this weekend unhappy , When can you notice me.  unhappy  what?  , Ahhhhh! You recognized LOGAN!!! Cinemax shows have a BAD track record for getting cancelled unhappy , Errr dude.... They're gone unhappy  Asked other league memeber to check  the guys are go , Not you again sad  , Why would Harvey be going to prison? unhappy , Missing in crying  Seaside area. , Becoz if we will depend on your promoting its waste of hardwork to all team who , I thought you'll save me crying , major waffle cravings right now sad , cant speak japanese ::(, how can people do stuff like this unhappy  , please just stop confining animals in zoos unhappy  , Feel like i shoyould be telling you to get the fuck out social media byout also feel really mean because unhappy  silence  love yoyou hope yoyoure okay , i miss you huhu so busy unhappy , it was extended family. 12 ppl.ahh wanted to show a Oh My Girl being dorky while playing a game but it got deleted unhappy , Don't do that unhappy , Jamie can you please reset the CGa grandfinal server... no administrator are responding unhappy , noOoooooo YOU GONNA MISS THE BUFFET unhappy  TAKE CARE AIN!!!!!!!!!!!!!!!!! , I wish i could vote for you unhappy , instant message so jealous okay unhappy  but never mind haha bruno can wait finals first, when i'm enlisting can please turn up like this unhappy  , unhappy  how come people like this have children where's the state intervention , Ouchhhhh unhappy  , Help... I want to stop tweeting. All I feel is endless suffering and pain. I tried to deactivate myself many times... Save me... unhappy , For those asking,  the application is Kana Kanji Funtime! Sadly,  it looks like iOS 11 is due to kill it unhappy  , Yeah did update to 16.04 ,  it froze a few times. Then went to 16.10,  froze mid install. Waited 3hrs he'd to pull plug crying , Shaandaar,  Zabardast,  Another ATBB on it's way ! I wish Srk Sir starts signing good movies unhappy  , I want Jabee crying , sociopath full raid gear sad  , When will you say hi sunshine ? unhappy  , i feel bad for doing that AHAHA unhappy , it's getting harder and harder to stay unhappy , His face looks bloated unhappy  baby get well soon , fuck. tried changing my settings but still in india. unhappy , talking to my over driver about where I'm goinghe said he'd love to go to New York too but since Trump it's probably not.1, Let's not forget that it's also Gabriel Tenma White's birthday today!I miss unhappy  , Why am i always taken for granted eversince unhappy , Ah alright,  i don%27t know if you saw my comment yet,  but what camera you shooting with,  does it have flip out scr , I miss Louis' tweets unhappy , Koalas are dying of thirst  and it's all because of us unhappy  , okay I'll shut up now. instant message just mad that lots of people will now have a VERY flawed opinion on mental health ( on mine) because of this show unhappy , pamura isa because in this very moment,  i want to explode like a grenade to the point where people will die with me. sad , YG should have sent them to MCD. I want to see them holding the trophy unhappy  anyways , i really want one of those iconic jimin stripes turtleneck shirt unhappy , I want a spoons but I cant go unhappy  honestly feels like a messy break up unhappy , Makes me so sad unhappy  they looked so unhappy when I went to SeaWorld , YG should have sent them to MCD. I want to see them holding the trophy unhappy  anyways .1, I miss Rockys posts unhappy  , Hey Tony,  oh no unhappy  Could you please tell me a little more about your issue? Im following if youd prefer to DM. Amanda, i love mason and miss mason unhappy , Cold as a mother crusher right now. Nearing the end of April. sad , we don%27t talk anymore like we used to do unhappy , YG should have sent them to MCD. I want to see them holding the trophy unhappy  anyways .2, miss biking unhappy , I miss Big brother unhappy , 6 days in camp haiss miss you a lot unhappy , It's raining so hard unhappy , Am bored and kandowiandg I have ando plaands for today is makiandg me eveand more bored unhappy , oh my god not laurie penny unhappy , can you say Hi Mekisha? unhappy , I should never draw again unhappy , Cleantha , Visual Studio Installation - 89% .. BSOD comes suddenly unhappy , i want to make waffles unhappy , So sad unhappy  , crying  muh feels, Look like somethings i will ignore xD Kart Racing when? unhappy , did ate jenna just blocked me or what? unhappy , My bed is so comfortable I don't want to get up unhappy , Is that store still in use? If so,  I sincerely hope not too many priceless antiques were destroyed. Reg , Astaga unhappy  /? , I want a puppy now unhappy , have to work unhappy  but i'll see you tomorrow!! , happy weed day without them is not the same anymore unhappy , my favourite lipstick hilang crying , Time just flies,  can't believe he will be year for next year unhappy  We're becoming old HAHAHAH :v, The new Twitter reply view has me confused... like do I capitalise my replies to people or not? unhappy , ...]
Index: []

[0 rows x 1117 columns]

In [7]:
data_neutral.head(5)

Empty DataFrame
Columns: [Pak PM survives removal scare,  but court orders further probe into corruption charge. , Supreme Court quashes criminal complaint against cricketer for allegedly depicting himself as on magazine cover., Art of Living's fights back over Yamuna floodplain damage,  livid. , FCRA slap on NGO for lobbying...But was it doing so as part of govt campaign? , Why doctors,  pharma companies are opposing names on , Why a bicycle and not a CM asked. His officer learnt ground reality -- and  a dip in a river. , It's 2017. making law to ban And MHA is sitting on draft. , Rivals govts unite to act against sex-determination tests. , Haryana peasants demand justice for right to cattle trade. , Why schools in Calcutta (and elsewhere) are stunned by imposition plan. , Why renamed places in , Oooh! the shame,  the trauma... of driving without the red,  flashing light. (And paying for parking). , Now have to learn to live without that flashing red light. , BJP leaders in the dock,  lose their light,  naming game,  and more. Also in epaper. , UK Parliament votes by 522 to 13 in favour of early national , April 19 1906: Nobel Laureate Pierre Curie was run over by a horse-drawn wagon near the Pont Neuf,  Paris,  and killed , India to end culture of sirens on cars. , From May 1,  only on vehicles: Gadkari., No from now on cars of PM,  ministers: transport minister Nitin Gadkari after Cabinet meet. , 44 feared killed as bus falls into River Tons in Nerwa area of district: police. , BSF dismisses Constable Tej Bahadur Yadav from service after a court of inquiry. Bad quality food allegations were base, jawan Tej Bahadur Yadav,  who took to social media complaining of bad food,  dismissed from service after inquiry., U.S. to review lifting of sanctions on Iran: Tillerson , Huge haul of milk-boosting hormone in Calcutta. , Good news from it seems are thriving at Valmiki reserve. , In Sushil Modi lists property chain. , 3 queens take centrestage. , A peek into FIR against leaders in case. , Spurned by mom,  this baby at Calcutta has died. , India may make it illegal for social messaging platforms to share personal data. , Why extradition could take ages. , March 20. Plus 15 days. Equals..., KP Nayar on why discrediting military justice system will not help case. , Sharad wants Gujarat CM arrested for trying to push making meat a communal issue.  , Man shouts at wife in family court. And walks out. , Overburdened says it may not be able to hold for college teachers this year. , President backs move to make mandatory up to Class X. , Nationalist trend spreads-- tightens rules to shield local jobs (and keep out Indians). , Visa 'selfie' by CBSE's plans,  blessing,  cloud over and more. Also in epaper. , Scotland Yard arrests in London,  but court grants him bail. , Liquor baron declared a proclaimed offender,  on extradition warrant: Scotland Yard., British Prime Minister Theresa May says she wants to hold early election on June 8: Reuters,  quoting BBC , Supreme Court seeks govt's response on a plea to frame national policy to promote and , JK: Schools  colleges shut down after clashes,  demands Presidential rule , Beetle from grips litchi crop in , Supreme Court asks govt to explain why need pre-censorship.  , US NSA H.R. to arrive in today; to hold talks with NSA , Why you should shun water at beaches. , Having lost Kerala bypoll,  won't have to keep its promise of 'good quality , So,  is -- and not to blame for stipend crisis faced by 4000 scholars? , The middleman (or conman) nephew tapped to bribe election commission officials. , Can  Air India enforce fines on unruly passengers for , Top law advisor backs use of human shield,  but some veteran generals see breach. , Arrest of a conman and bribe charges against nephew churns politics. , How cloaked debate in Draupadi's robes. , Draupadi and campuses in erupt,  politics,  and more. Also in epaper. .1, CBI books 12 leaders in case. , Supreme Court summons boss,  orders sale of slice. , SC summons Home Secretaries of West Bengal,  UP,  Karnataka,  Tamil Nadu,  Bihar  Jharkhand for nice try filling police vacancie, Manini Chatterjee on why writings are still an indictment of India. , Why wants paper trail in elections. , Govt to set up panel to study service conditions of paramilitary forces. , Amit Roy on an potboiler.  , Muslim body lays down code of conduct during divorce,  but won't ban , Modi's call to ensure justice for women facing evil customs.  , PM's pitch for sisters,  board's stand on an potboiler. And more. Also in epaper. , Why the always meets this man when he visits eastern India. , ...]
Index: []

[0 rows x 1570 columns]

In [8]:
data_positive.head(5)

Empty DataFrame
Columns: [An inspiration in all aspects: Fashion,  fitness,  beauty and personality. :)KISSES TheFashionIcon, Apka Apna Awam Ka Channel Frankline Tv Aam Admi Production Please Visit Or Likes  Share :)Fb Page :..., Beautiful album from  the greatest unsung guitar genius of our time - and I've met the great backstage, Good luck to Rich riding for great project in this Sunday. Can you donate?, Omg he... kissed... him crying with joy, happy anniv ming and papi!!!!! love love happy, thanks happy, C'mon Tweeps,  Join  vote for the singer! Do spread the word. :D, Thanks for the great review! smile, Yay another art raffle! Everything you need to know is in the picture :D, Hello I hope you visit Luxor its amazing city in Egypt pleas check, We got a Vive tracker in the office and our intern,  went to work.Don't get too excited,  this isn't, Take a look at favourites.io You can do this and more happy, Go back to school for music! I think I will in time happy, Sixth spot not applicable Team! Higher pa! :)KISSES TheFashionIcon, thanks for being top influencers in my community last week happy, Share the love: thanks for being top new followers this week happy  Want this?, retweet this tweet if you want your to be included in the nhc scrapbook!! i'll be making something out of all of the usern, Happy 420 happy  pass it to your followers!, Who wants some good vibes? Watch this on YouTube or TV100 application now for FREE happy, Great to work with you too such a lovely place! Thank you for havin, Nothing is ever as it seems. What looks bad today,  will be a blessing tomorrow happy  Keep your faith stirred up each day!, Mmmmmmmm love naughty wives smile, You deserve a vacation happy, Never known how hard it is until last to  days how to resist temptation to enter politics debates on social media happy  stood firm so far, Some summer salad inspiration for the BBQ smile, Hey thanks for being top new followers this week! Much appreciated happy  Want this ?, you should post this offer on this website happy, thanks for being top new followers - have a great week happy, I prefer it to sharm - enjoy it happy  Gouna 20km away is also quite nice - honestly anywhere away from crazy cairo is, Sixth spot not applicable Team! Higher pa! :)KISSES TheFashionIcon.1, Hey thanks for being top new followers this week! Much appreciated happy, thanks for the recent follow. Much appreciated happy, Thanks Lala.. Much needed happy, Thanks for connecting We are passionate about  - hope you like our tweets happy, hey,  keep smiling happy, Said it yesterday... happy, We love that our bloggers love us so much happy  Thank you for such an amazing review The Perfect Glasses h, only way to make sense of those crazy edge cases is the idea of sharing revenue was offensive,  rather, Gentle reminder on our TP guidelines happy  please read and spread. Thank you. happy KISSES TheFashionIcon, keep being you,  cheeky :D, smile  So true. For someone who was being recognised for her contribution to fashion,  she might have dressed a bit better., sounds like a lot of fun :D I like it, Oh,  Jin was spotted at Everland today. Nice to see them having a break after the US tour happy, There was nothing religious in it. is calling out sexism. I don't think I need to spell out my stand, Go back to school for music! I think I will in time happy.1, Theres only one thing I want to change about you . Your Last Name happy  ALDUBOnly, welcome brother  happy, Thanks for the recent follow Happy to connect happy  have a great Thursday., SONE who cant stream at Genie!You CAN stream for TY at Genie! We are still sharing some Genie IDs. If you want it,  DM us happy  S, Spending time with dogs or other animals is great at helping you to relax and de-stress. Great idea happy, My new video for happy  I hope you like ithappy, Got This interview poppin happy  $$$$$, Love your tweetability! We'd like to reach out to with an opportunity! Could you hit us with your email happy, Thanks for the recent follow Happy to connect happy  have a great Thursday..1, uss,  I'll DM you half naked pictures happy, Evet happy, Well,  I hope it doesn't last too long and you at least get to enjoy the weekend. And happy birthday again happy, Excited about event next week in Bangalore!  come happy, Want to win a pet chick happy  Simply follow  retweet for your chance to win! Winners will be selected Sunday 23rd. Go, Top retweeters this week,  Thank you happy, dope!! that's a cool word. finally down with the hip young millenial memers smile, 2nd Cousin Vlad !!!!! maybe thats a message from the Hockey G, Thanks for the recent follow Happy to connect happy  have a great Thursday. (Want this?, Earlier happy, Just win at weekend and it will be a late gift,  ok? :D, we finally got jinyoung to wipe it for jaebum himself but their precious son blocks it for the world to witness it, Here is question 18! Make sure to use in all your tweets  replies happy, And this credit also goes to Ik happy, My other accounts:them both or get rekt! :D, Hey thanks for being top new followers this week! Much appreciated happy.1, Les videre happy, clauditte, my friend is such an egg, congratulations David! Well done Mrs V! Welcome Jessica! happy, have you tried these new hacks?! **TRYING DUMB LIFE HACKS 17**, Keep tweeting team. Higher! Thank you for the efforts. :)KISSES TheFashionIcon, here are some very happy boys to brighten up your day happy, A huge thank you to all the within the Social Work  Care Sectors! Keep up the great work happy, Lunchtime with Flinthook! This game has so much personality :D, Ministers of PMLN are happy like those students who never studied for exams  luckily exams got delayed. They'll still ha, :D When mom is a bit tired, What we did after the climax shot happy, Miss Petite happy Thursday happy   looking forward to the weekend?, ...]
Index: []

[0 rows x 1186 columns]

In [6]:
data_negative = data_negative.T
data_neutral = data_neutral.T
data_positive = data_positive.T

In [95]:
print(data_negative.shape)
print(data_neutral.shape)
print(data_positive.shape)

(1117, 0)
(1570, 0)
(1186, 0)

In [7]:
data_negative['sentement'] = 'negative'
data_neutral['sentement'] = 'neutral'
data_positive['sentement'] = 'positive'

In [8]:
data_negative.index.name = 'sentence'
data_neutral.index.name = 'sentence'
data_positive.index.name = 'sentence'

In [98]:
data_positive.head(5)

                                                   sentement
sentence
An inspiration in all aspects: Fashion              positive
 fitness                                            positive
 beauty and personality. :)KISSES TheFashionIcon    positive
Apka Apna Awam Ka Channel Frankline Tv Aam Admi...  positive
Beautiful album from  the greatest unsung guita...  positive

In [9]:
df = pd.concat([data_negative, data_neutral, data_positive])

In [10]:
import re

leak_words = ['happy', 'unhappy']

def remove_leak(text):
    text = str(text)
    for w in leak_words:
        text = re.sub(rf'\b{w}\b', '', text, flags=re.IGNORECASE)
    return text.strip()

df.index = df.index.map(remove_leak)

In [101]:
df.sample(5)

                                                   sentement
sentence
if i get 900 retweets and 900 likes. help me :(...  negative
we don%27t talk anymore like we used to do          negative
Why may not show in                                  neutral
Superstar thanks so much for the kind words! Lo...  positive
I dohn't want toh cohmment ohn it: Amit Shah oh      neutral

In [102]:
df.shape

(3873, 1)

Splitting (80/20, stratified by 'sentement')

In [18]:
train, test = train_test_split(df, test_size=0.2, stratify=df['sentement'])

In [104]:
print(test.head(3))
print(test.head(3))
print(' ')
print(f'Train size: {train.shape}')
print(f'Test size: {test.shape}')

                                                   sentement
sentence
Your titties are fantastic. Kissy Kissy             positive
I love it when Ben sleeps in because I get to w...  positive
How the formidable Madame of Calcutta's runs he...   neutral
                                                   sentement
sentence
Your titties are fantastic. Kissy Kissy             positive
I love it when Ben sleeps in because I get to w...  positive
How the formidable Madame of Calcutta's runs he...   neutral

Train size: (3098, 1)
Test size: (775, 1)

Our plan of 21 different experiments:

|          | 0/1 (if word exists) | word counts | TFIDF |
|---|---|---|---|
| just tokenization | | | |
| stemming | | | |
| lemmatization | | | |
| stemming + misspellings | | | |
| lemmatization + misspellings | | | |
| stemming + misspellings + stop-words | | | |
| lemmatization + misspellings + stop-words | | | |

In [19]:
X_train = train.index.astype(str)
y_train = train['sentement']
X_test  = test.index.astype(str)
y_test  = test['sentement']

1. **Just tokenization**

In [106]:
vectorizer = CountVectorizer(binary=True)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec  = vectorizer.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)
preds = model.predict(X_test_vec)

print("0/1:", accuracy_score(y_test, preds))

0/1: 0.7651612903225806

In [107]:
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec  = vectorizer.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)
preds = model.predict(X_test_vec)

print("word counts:", accuracy_score(y_test, preds))

word counts: 0.7574193548387097

In [108]:
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec  = vectorizer.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)
preds = model.predict(X_test_vec)

print("TFIDF:", accuracy_score(y_test, preds))

TFIDF: 0.7612903225806451

2. **Stemming**

In [24]:
import nltk
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')

stemmer = PorterStemmer()

[nltk_data] Downloading package punkt to /Users/ggang/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /Users/ggang/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [21]:
def apply_stemming(text):
    words = word_tokenize(text)
    stemmed = [stemmer.stem(w) for w in words]
    return ' '.join(stemmed)

In [111]:
X_train_stem = X_train.map(apply_stemming)
X_test_stem  = X_test.map(apply_stemming)

In [112]:
vectorizer = CountVectorizer(binary=True)
X_train_stem_vec = vectorizer.fit_transform(X_train_stem)
X_test_stem_vec  = vectorizer.transform(X_test_stem)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_stem_vec, y_train)
preds = model.predict(X_test_stem_vec)

print("0/1:", accuracy_score(y_test, preds))

0/1: 0.7625806451612903

In [113]:
vectorizer = CountVectorizer()
X_train_stem_vec = vectorizer.fit_transform(X_train_stem)
X_test_stem_vec  = vectorizer.transform(X_test_stem)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_stem_vec, y_train)
preds = model.predict(X_test_stem_vec)

print("word counts:", accuracy_score(y_test, preds))

word counts: 0.7664516129032258

In [114]:
vectorizer = TfidfVectorizer()
X_train_stem_vec = vectorizer.fit_transform(X_train_stem)
X_test_stem_vec  = vectorizer.transform(X_test_stem)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_stem_vec, y_train)
preds = model.predict(X_test_stem_vec)

print("TFIDF:", accuracy_score(y_test, preds))

TFIDF: 0.7677419354838709

3. **Lemmatization**

In [115]:
from nltk.stem import WordNetLemmatizer

nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()

def apply_lemmatization(text):
    words = word_tokenize(str(text))
    lemmas = [lemmatizer.lemmatize(w) for w in words]
    return ' '.join(lemmas)

[nltk_data] Downloading package wordnet to /Users/ggang/nltk_data...

In [116]:
X_train_lemm = X_train.map(apply_lemmatization)
X_test_lemm  = X_test.map(apply_lemmatization)

In [117]:
vectorizer = CountVectorizer(binary=True)
X_train_lemm_vec = vectorizer.fit_transform(X_train_lemm)
X_test_lemm_vec  = vectorizer.transform(X_test_lemm)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_lemm_vec, y_train)
preds = model.predict(X_test_lemm_vec)

print("0/1:", accuracy_score(y_test, preds))

0/1: 0.7664516129032258

In [118]:
vectorizer = CountVectorizer()
X_train_lemm_vec = vectorizer.fit_transform(X_train_lemm)
X_test_lemm_vec  = vectorizer.transform(X_test_lemm)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_lemm_vec, y_train)
preds = model.predict(X_test_lemm_vec)

print("word counts:", accuracy_score(y_test, preds))

word counts: 0.7651612903225806

In [119]:
vectorizer = TfidfVectorizer()
X_train_lemm_vec = vectorizer.fit_transform(X_train_lemm)
X_test_lemm_vec  = vectorizer.transform(X_test_lemm)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_lemm_vec, y_train)
preds = model.predict(X_test_lemm_vec)

print("TFIDF:", accuracy_score(y_test, preds))

TFIDF: 0.7625806451612903

4. **Stemming + Misspellings**

In [22]:
from spellchecker import SpellChecker

spell = SpellChecker()

def fix_misspellings(text):
    words = str(text).split()
    fixed = []
    for w in words:
        correction = spell.correction(w)
        fixed.append(correction if correction else w)
    return ' '.join(fixed)

In [ ]:
X_train_spel = X_train.map(fix_misspellings)
X_train_stem_spel = X_train_spel.map(apply_stemming)
X_test_spel = X_test.map(fix_misspellings)
X_test_stem_spel  = X_test_spel.map(apply_stemming)

In [142]:
vectorizer = CountVectorizer(binary=True)
X_train_stem_spel_vec = vectorizer.fit_transform(X_train_stem_spel)
X_test_stem_spel_vec  = vectorizer.transform(X_test_stem_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_stem_spel_vec, y_train)
preds = model.predict(X_test_stem_spel_vec)

print("0/1:", accuracy_score(y_test, preds))

0/1: 0.7741935483870968

In [143]:
vectorizer = CountVectorizer()
X_train_stem_spel_vec = vectorizer.fit_transform(X_train_stem_spel)
X_test_stem_spel_vec  = vectorizer.transform(X_test_stem_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_stem_spel_vec, y_train)
preds = model.predict(X_test_stem_spel_vec)

print("word counts:", accuracy_score(y_test, preds))

word counts: 0.7741935483870968

In [144]:
vectorizer = TfidfVectorizer()
X_train_stem_spel_vec = vectorizer.fit_transform(X_train_stem_spel)
X_test_stem_spel_vec  = vectorizer.transform(X_test_stem_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_stem_spel_vec, y_train)
preds = model.predict(X_test_stem_spel_vec)

print("TFIDF:", accuracy_score(y_test, preds))

TFIDF: 0.7793548387096774

5. **Lemmatization + Misspellings**

In [ ]:
X_train_spel = X_train.map(fix_misspellings)
X_train_lemm_spel = X_train_spel.map(apply_lemmatization)
X_test_spel = X_test.map(fix_misspellings)
X_test_lemm_spel  = X_test_spel.map(apply_lemmatization)

In [146]:
vectorizer = CountVectorizer(binary=True)
X_train_lemm_spel_vec = vectorizer.fit_transform(X_train_lemm_spel)
X_test_lemm_spel_vec  = vectorizer.transform(X_test_lemm_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_lemm_spel_vec, y_train)
preds = model.predict(X_test_lemm_spel_vec)

print("0/1:", accuracy_score(y_test, preds))

0/1: 0.7651612903225806

In [147]:
vectorizer = CountVectorizer()
X_train_lemm_spel_vec = vectorizer.fit_transform(X_train_lemm_spel)
X_test_lemm_spel_vec  = vectorizer.transform(X_test_lemm_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_lemm_spel_vec, y_train)
preds = model.predict(X_test_lemm_spel_vec)

print("word counts:", accuracy_score(y_test, preds))

word counts: 0.7703225806451612

In [148]:
vectorizer = TfidfVectorizer()
X_train_lemm_spel_vec = vectorizer.fit_transform(X_train_lemm_spel)
X_test_lemm_spel_vec  = vectorizer.transform(X_test_lemm_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_lemm_spel_vec, y_train)
preds = model.predict(X_test_lemm_spel_vec)

print("TFIDF:", accuracy_score(y_test, preds))

TFIDF: 0.7716129032258064

6. **Stemming + Misspellings + Stop_words**

In [ ]:
X_train_spel = X_train.map(fix_misspellings)
X_train_stem_spel = X_train_spel.map(apply_stemming)
X_test_spel = X_test.map(fix_misspellings)
X_test_stem_spel  = X_test_spel.map(apply_stemming)

In [150]:
vectorizer = CountVectorizer(binary=True, stop_words='english')
X_train_stem_spel_vec = vectorizer.fit_transform(X_train_stem_spel)
X_test_stem_spel_vec  = vectorizer.transform(X_test_stem_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_stem_spel_vec, y_train)
preds = model.predict(X_test_stem_spel_vec)

print("0/1:", accuracy_score(y_test, preds))

0/1: 0.7496774193548387

In [151]:
vectorizer = CountVectorizer(stop_words='english')
X_train_stem_spel_vec = vectorizer.fit_transform(X_train_stem_spel)
X_test_stem_spel_vec  = vectorizer.transform(X_test_stem_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_stem_spel_vec, y_train)
preds = model.predict(X_test_stem_spel_vec)

print("word counts:", accuracy_score(y_test, preds))

word counts: 0.7496774193548387

In [152]:
vectorizer = TfidfVectorizer(stop_words='english')
X_train_stem_spel_vec = vectorizer.fit_transform(X_train_stem_spel)
X_test_stem_spel_vec  = vectorizer.transform(X_test_stem_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_stem_spel_vec, y_train)
preds = model.predict(X_test_stem_spel_vec)

print("TFIDF:", accuracy_score(y_test, preds))

TFIDF: 0.7483870967741936

7. **Lemmatization + Misspellings + Stop_words**

In [ ]:
X_train_spel = X_train.map(fix_misspellings)
X_train_lemm_spel = X_train_spel.map(apply_lemmatization)
X_test_spel = X_test.map(fix_misspellings)
X_test_lemm_spel  = X_test_spel.map(apply_lemmatization)

In [154]:
vectorizer = CountVectorizer(binary=True, stop_words='english')
X_train_lemm_spel_vec = vectorizer.fit_transform(X_train_lemm_spel)
X_test_lemm_spel_vec  = vectorizer.transform(X_test_lemm_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_lemm_spel_vec, y_train)
preds = model.predict(X_test_lemm_spel_vec)

print("0/1:", accuracy_score(y_test, preds))

0/1: 0.7445161290322581

In [155]:
vectorizer = CountVectorizer(stop_words='english')
X_train_lemm_spel_vec = vectorizer.fit_transform(X_train_lemm_spel)
X_test_lemm_spel_vec  = vectorizer.transform(X_test_lemm_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_lemm_spel_vec, y_train)
preds = model.predict(X_test_lemm_spel_vec)

print("word counts:", accuracy_score(y_test, preds))

word counts: 0.7393548387096774

In [156]:
vectorizer = TfidfVectorizer(stop_words='english')
X_train_lemm_spel_vec = vectorizer.fit_transform(X_train_lemm_spel)
X_test_lemm_spel_vec  = vectorizer.transform(X_test_lemm_spel)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_lemm_spel_vec, y_train)
preds = model.predict(X_test_lemm_spel_vec)

print("TFIDF:", accuracy_score(y_test, preds))

TFIDF: 0.7303225806451613

**Final results:**

|          | 0/1 (if word exists) | word counts | TFIDF |
|---|---|---|---|
| just tokenization | 0.7651|0.7574 | 0.7613|
| stemming | 0.7626| 0.7665|0.7677 |
| lemmatization |0.7665 |0.7652 | 0.7626|
| stemming + misspellings |0.7742 | 0.7742| 0.7794|
| lemmatization + misspellings |0.7652 | 0.7703| 0.7716|
| stemming + misspellings + stop-words | 0.7497| 0.7497| 0.7484|
| lemmatization + misspellings + stop-words |0.7445 |0.7394 | 0.7303|

8. **Custom pipeline - misspelling + stemming + vec(TFIDF with params) + logreg**

In [ ]:
X_train_spel = X_train.map(fix_misspellings)
X_test_spel  = X_test.map(fix_misspellings)
X_train_spel_stem = X_train_spel.map(apply_stemming)
X_test_spel_stem  = X_test_spel.map(apply_stemming)

In [158]:
vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.9,
    sublinear_tf=True
)
X_train_vec = vectorizer.fit_transform(X_train_spel_stem)
X_test_vec  = vectorizer.transform(X_test_spel_stem)

In [162]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)
preds = model.predict(X_test_vec)

print("misspelling + stemming + TFIDF(tuned) + LogReg:", accuracy_score(y_test, preds))

misspelling + stemming + TFIDF(tuned) + LogReg: 0.7806451612903226

**Similarity**

In [1]:
from sklearn.metrics.pairwise import cosine_similarity

In [14]:
texts = df.index.to_series().reset_index(drop=True)
texts = texts.astype(str)

vectorizer = TfidfVectorizer()
tfidf = vectorizer.fit_transform(texts)
print("matrix shape:", tfidf.shape)

matrix shape: (3873, 6433)

In [15]:
sim = cosine_similarity(tfidf)
print("proximity matrix:", sim.shape)

proximity matrix: (3873, 3873)

In [17]:
sim_clean = np.triu(sim, k=1)

N = 10
flat = sim_clean.flatten()
top_idx = flat.argsort()[-N:][::-1]

print(f"Top-{N} similarity tweets:\n")
for idx in top_idx:
    i, j = np.unravel_index(idx, sim.shape)
    score = sim[i, j]
    print(f"score = {score:.3f}")
    print(f"  [{i}] {texts.iloc[i]}")
    print(f"  [{j}] {texts.iloc[j]}")
    print()

Top-10 similarity tweets:

score = 1.000
  [3219] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.1
  [3343] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.2

score = 1.000
  [3219] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.1
  [3805] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.4

score = 1.000
  [3343] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.2
  [3805] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.4

score = 1.000
  [3343] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.2
  [3696] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.3

score = 1.000
  [3360] have a great Thursday! Looking forward to reading your tweets   Want this ?
  [3408] have a great Thursday! Looking forward to reading your tweets   Want this

score = 1.000
  [3408] have a great Thursday! Looking forward to reading your tweets   Want this
  [3821] have a great Thursday! Looking forward to reading your tweets    Want this

score = 1.000
  [1355] Ram Madhav tells
  [1372] Ram Madhav tells .1

score = 1.000
  [3163] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile
  [3805] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.4

score = 1.000
  [3163] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile
  [3696] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.3

score = 1.000
  [3163] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile
  [3343] Superstar thanks so much for the kind words! Look forward to seeing you soon buddy smile.2

**Different algorithms**

In [25]:
X_train_spel = X_train.map(fix_misspellings)
X_test_spel  = X_test.map(fix_misspellings)
X_train_prep = X_train_spel.map(apply_stemming)
X_test_prep  = X_test_spel.map(apply_stemming)

vectorizer = TfidfVectorizer(ngram_range=(1, 2), min_df=2, max_df=0.9, sublinear_tf=True)
X_train_vec = vectorizer.fit_transform(X_train_prep)
X_test_vec  = vectorizer.transform(X_test_prep)
print("features:", X_train_vec.shape[1])

features: 4054

In [26]:
from sklearn.linear_model import SGDClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB, ComplementNB

models = {
    "LogisticRegression": LogisticRegression(max_iter=1000, class_weight='balanced'),
    "LinearSVC":          LinearSVC(class_weight='balanced'),
    "SGDClassifier":      SGDClassifier(max_iter=1000, class_weight='balanced'),
    "MultinomialNB":      MultinomialNB(),
    "ComplementNB":       ComplementNB(),
}

results = {}
for name, m in models.items():
    m.fit(X_train_vec, y_train)
    acc = accuracy_score(y_test, m.predict(X_test_vec))
    results[name] = acc
    print(f"{name:20s}: {acc:.4f}")

LogisticRegression  : 0.7910
LinearSVC           : 0.7794
SGDClassifier       : 0.7574
MultinomialNB       : 0.7935
ComplementNB        : 0.7935