In [1]:
import pandas as pd

views = pd.read_csv('../feed-views.log',
                    delimiter='\t',
                    names=['datetime', 'user'], header=None,
                    )

views.shape

(1076, 2)

In [2]:
views.dtypes

datetime    object
user        object
dtype: object

In [3]:
views['datetime'] = views['datetime'].astype('datetime64[ns]')

In [4]:
views.dtypes

datetime    datetime64[ns]
user                object
dtype: object

In [5]:
views['year']   = views['datetime'].dt.year
views['month']  = views['datetime'].dt.month
views['day']    = views['datetime'].dt.day
views['hour']   = views['datetime'].dt.hour
views['minute'] = views['datetime'].dt.minute
views['second'] = views['datetime'].dt.second

views.head(2)

                    datetime   user  year  month  day  hour  minute  second
0 2020-04-17 12:01:08.463179  artem  2020      4   17    12       1       8
1 2020-04-17 12:01:23.743946  artem  2020      4   17    12       1      23

In [6]:
views = views.set_index('user')

bins = [0, 4, 7, 11, 17, 20, 24]
labels = ['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening']
views['daytime'] = pd.cut(views['hour'], bins=bins, labels=labels, include_lowest=True)

views.sample(2)

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-05-12 00:26:30.724998,2020,5,12,0,26,30,night
pavel,2020-05-12 21:52:50.968227,2020,5,12,21,52,50,evening

In [7]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [8]:
views['daytime'].value_counts()

daytime
evening          445
afternoon        279
early evening    144
night            134
morning           74
early morning      0
Name: count, dtype: int64

In [9]:
views.sort_values(['hour', 'minute', 'second'], ascending=True, inplace=True)

In [10]:
views.head()

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
valentina,2020-05-15 00:00:13.222265,2020,5,15,0,0,13,night
valentina,2020-05-15 00:01:05.153738,2020,5,15,0,1,5,night
pavel,2020-05-12 00:01:27.764025,2020,5,12,0,1,27,night
pavel,2020-05-12 00:01:38.444917,2020,5,12,0,1,38,night
pavel,2020-05-12 00:01:55.395042,2020,5,12,0,1,55,night

In [11]:
print(f"Min hour:", views['hour'].min())
print(f"Max hour:", views['hour'].max())

Min hour: 0
Max hour: 23

In [12]:
print(f"Mode of daytime:", views['daytime'].mode()[0])

Mode of daytime: evening

In [13]:
print(f"Max hour where daytime is night:", views[views['daytime']=='night']['hour'].max())
print(f"Min hour where daytime is morning:", views[views['daytime']=='morning']['hour'].min())

Max hour where daytime is night: 4
Min hour where daytime is morning: 8

In [14]:
print(f"User where night is max:", views[(views['daytime'] == 'night') & (views['hour'] == views[views['daytime']=='night']['hour'].max())].head(1).index[0])
print(f"User where morning is min:", views[(views['daytime'] == 'morning') & (views['hour'] == views[views['daytime']=='morning']['hour'].min())].head(1).index[0])

User where night is max: konstantin
User where morning is min: alexander

In [15]:
print(f"Mode of hour:", views['hour'].mode()[0])
print(f"Mode of daytime:", views['daytime'].mode()[0])

Mode of hour: 22
Mode of daytime: evening

In [16]:
print(f"3 users with smallest time in the morning:", views[views['daytime']=='morning']['hour'].nsmallest(3))
print(f"3 users with largest time in the morning:", views[views['daytime']=='morning']['hour'].nlargest(3))

3 users with smallest time in the morning: user
alexander    8
alexander    8
alexander    9
Name: hour, dtype: int32
3 users with largest time in the morning: user
artem    11
artem    11
artem    11
Name: hour, dtype: int32

In [17]:
iqr = views['hour'].describe()['75%'] - views['hour'].describe()['25%']
print(iqr)

9.0