# Day 09. Exercise 02
# Metrics

## 0. Imports

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
import joblib

## 1. Preprocessing

1. Create the same dataframe as in the previous exercise.
2. Using `train_test_split` with parameters `test_size=0.2`, `random_state=21` get `X_train`, `y_train`, `X_test`, `y_test`. Use the additional parameter `stratify`.

In [2]:
df = pd.read_csv("../ex01/day-of-week-not-scaled.csv")
df2 = pd.read_csv("../ex00/dayofweek.csv")
df['dayofweek'] = df2['dayofweek']
print(df.shape)
print(df.dtypes.to_list())
df.head()

(1686, 44)
[dtype('int64'), dtype('int64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('int64')]

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1,dayofweek
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4

In [3]:
random_state=21
test_size=0.2
X = df.drop('dayofweek', axis=1)
y = df['dayofweek']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=random_state, test_size=test_size, stratify=y)
print('X_train shape: ', X_train.shape)
print('y_train shape: ', y_train.shape)
print('X_test shape : ', X_test.shape)
print('y_test shape : ', y_test.shape)

X_train shape:  (1348, 43)
y_train shape:  (1348,)
X_test shape :  (338, 43)
y_test shape :  (338,)

## 2. SVM

1. Use the best parameters from the previous exercise and train the model of SVM.
2. You need to calculate `accuracy`, `precision`, `recall`, `ROC AUC`.

 - `precision` and `recall` should be calculated for each class (use `average='weighted'`)
 - `ROC AUC` should be calculated for each class against any other class (all possible pairwise combinations) and then weighted average should be applied for the final metric
 - the code in the cell should display the result as below:

```
accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878
```

In [4]:
model1 = SVC(random_state=random_state, probability=True, C=10, class_weight=None, gamma='auto', kernel='rbf')
model1.fit(X_train, y_train)
predict = model1.predict(X_test)

accuracy = accuracy_score(y_test, predict)
precision = precision_score(y_test, predict, average='weighted')
recall = recall_score(y_test, predict, average='weighted')
roc_auc = roc_auc_score(y_test, model1.predict_proba(X_test), average='weighted', multi_class='ovo')

print(f"accuracy: {accuracy:.5f}")
print(f"precision: {precision:.5f}")
print(f"recall: {recall:.5f}")
print(f"roc_auc: {roc_auc:.5f}")

accuracy: 0.88757
precision: 0.89267
recall: 0.88757
roc_auc: 0.97878

## 3. Decision tree

1. The same task for decision tree

In [5]:
model2 = DecisionTreeClassifier(random_state=random_state, class_weight='balanced', criterion='gini', max_depth=21)
model2.fit(X_train, y_train)
predict = model2.predict(X_test)

accuracy = accuracy_score(y_test, predict)
precision = precision_score(y_test, predict, average='weighted')
recall = recall_score(y_test, predict, average='weighted')
roc_auc = roc_auc_score(y_test, model2.predict_proba(X_test), average='weighted', multi_class='ovo')

print(f"accuracy: {accuracy:.5f}")
print(f"precision: {precision:.5f}")
print(f"recall: {recall:.5f}")
print(f"roc_auc: {roc_auc:.5f}")

accuracy: 0.88462
precision: 0.88765
recall: 0.88462
roc_auc: 0.93528

## 4. Random forest

1. The same task for random forest.

In [6]:
model3 = RandomForestClassifier(random_state=random_state, class_weight='balanced', criterion='entropy', max_depth=24, n_estimators=100)
model3.fit(X_train, y_train)
predict = model3.predict(X_test)

accuracy = accuracy_score(y_test, predict)
precision = precision_score(y_test, predict, average='weighted')
recall = recall_score(y_test, predict, average='weighted')
roc_auc = roc_auc_score(y_test, model3.predict_proba(X_test), average='weighted', multi_class='ovo')

print(f"accuracy: {accuracy:.5f}")
print(f"precision: {precision:.5f}")
print(f"recall: {recall:.5f}")
print(f"roc_auc: {roc_auc:.5f}")

accuracy: 0.92604
precision: 0.92754
recall: 0.92604
roc_auc: 0.98939

## 5. Predictions

1. Choose the best model.
2. Analyze: for which `weekday` your model makes the most errors (in % of the total number of samples of that class in your full dataset), for which `labname` and for which `users`.
3. Save the model.

In [7]:
best_model = RandomForestClassifier(random_state=random_state, 
                                    class_weight='balanced',
                                    criterion='entropy', 
                                    max_depth=24, 
                                    n_estimators=100)

best_model.fit(X_train, y_train)

df_errors = pd.DataFrame({'y_true': y_test, 'y_pred': predict})
df_errors.head()

      y_true  y_pred
1087       1       1
16         5       5
563        6       6
1381       3       3
1199       2       2

In [8]:
errors_per_class = (df_errors['y_true'] != df_errors['y_pred']).groupby(df_errors['y_true']).sum()
total_per_class = df_errors['y_true'].value_counts()
error_percentage = (errors_per_class / total_per_class * 100).sort_values(ascending=False)

print(error_percentage)

0    22.222222
4    14.285714
5     9.259259
1     7.272727
2     6.666667
3     3.750000
6     2.816901
dtype: float64

In [9]:
joblib.dump(best_model, 'best_model.joblib')

['best_model.joblib']

## 6. Function

1. Write a function that takes a list of different models and a corresponding list of parameters (dicts) and returns a dict that contains all the 4 metrics for each model.

In [10]:
def calc_metrics(models, X_train, y_train, X_test, y_test):
    metrics = dict()
    for model in models:
        model.fit(X_train, y_train)
        predict = model.predict(X_test)

        accuracy = accuracy_score(y_test, predict)
        precision = precision_score(y_test, predict, average='weighted')
        recall = recall_score(y_test, predict, average='weighted')
        roc_auc = roc_auc_score(y_test, model.predict_proba(X_test), average='weighted', multi_class='ovo')
        metrics[model] = [f'acc - {accuracy:.5f}', f'pr - {precision:.5f}', f'rec - {recall:.5f}', f'roc - {roc_auc:.5f}']
    return metrics

In [11]:
model1 = SVC(random_state=random_state, probability=True, C=10, class_weight=None, gamma='auto', kernel='rbf')
model2 = DecisionTreeClassifier(random_state=random_state, class_weight='balanced', criterion='gini', max_depth=21)
model3 = RandomForestClassifier(random_state=random_state, class_weight='balanced', criterion='entropy', max_depth=24, n_estimators=100)

models = [model1, model2, model3]

calc_metrics(models, X_train, y_train, X_test, y_test)

{SVC(C=10, gamma='auto', probability=True, random_state=21): ['acc - 0.88757',
  'pr - 0.89267',
  'rec - 0.88757',
  'roc - 0.97878'],
 DecisionTreeClassifier(class_weight='balanced', max_depth=21, random_state=21): ['acc - 0.88462',
  'pr - 0.88765',
  'rec - 0.88462',
  'roc - 0.93528'],
 RandomForestClassifier(class_weight='balanced', criterion='entropy',
                        max_depth=24, random_state=21): ['acc - 0.92604',
  'pr - 0.92754',
  'rec - 0.92604',
  'roc - 0.98939']}